version: 2.1

aktion:
  echo "Gebe Umgebung aus" 
  ls -lart

jobs:
  opemode:
    docker:
      # - image: ubuntu-2004:202010-01
      - image: silex/emacs:27.2
    working_directory: ~/simple-paren
    steps:
      - run: apt update && apt install -y git ssh emacs
      - checkout
      - run:
          name: Umgebung
          command:
            echo "Gebe Umgebung aus"; ls -lart

      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
            --eval "(message (emacs-version))" \
            --eval "(message (getenv \"PWD\"))" \
            --eval "(load (expand-file-name \"simple-paren.el\"))" \
            --eval "(setq simple-paren-debug nil)" \
            --eval "(setq python-indent-offset 4)" \
            --eval "(setq python-indent-guess-indent-offset nil)" \
            --eval "(setq python-indent-guess-indent-offset-verbose nil)" \
            --eval "(load \"/root/simple-paren/test/simple-paren-setup-tests.el\")" \
            --eval "(load \"/root/simple-paren/test/simple-paren-emacs-lisp-tests.el\")" \
            --eval "(sit-for 1)" \
            -f ert-run-tests-batch-and-exit


workflows:
  opemode-workflow:
    jobs:
      - opemode  
